### ISSUE TITLE
[HANDSHAKE] [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by pixelflowxyz** [phin05/discord-rich-presence-plex#21]
Hey everyone.

Just trying to run this! I've installed the dependency and added my details, but i'm just not getting it over on Discord?
Here's the console output (running as admin too): https://pixelflow.elixi.re/i/jp6r.png

Here's my config file:
https://pastebin.com/y4MeGSLR

Any ideas?

**Comment by Phineas05** [comment]
Is your Discord client running on the same machine? Try restarting or updating Discord, if you haven't already.

**Comment by Soup666** [comment]
Did you ever solve this? Same issue

**Comment by jacobmix** [comment]
Seems to be an issue with sending to Discord Rich Presence.
Did you make sure websocket-client is version 0.48.0?
Else try uninstalling Python (all versions) and start over from the start.
There's step by step instructions [here](https://github.com/Phineas05/discord-rich-presence-plex/issues/20#issuecomment-625757212).

**Comment by phineas05** [comment]
Try using the latest version of the script by following the updated basic installation instructions in the [README](https://github.com/phineas05/discord-rich-presence-plex/blob/master/README.md) and see if your issue is resolved. Make sure that the Discord client is running on the same machine you're running the script on.

**Comment by Hinatabestwaifu** [comment]
same issue here, just returns 

> FileNotFoundError: [WinError 2] The system cannot find the file specified

and points to `Python\Python311\Lib\asyncio\windows_events.py"` 

> line 338, in create_pipe_connection
    pipe = await f
    
> line 681, in connect_pipe
    handle = _overlapped.ConnectPipe(address)

**Comment by phin05** [comment]
This should be fixed in [v2.4.2](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.4.2).

Discord's IPC pipe name can end with a number in the range of `0-9`. When a Discord client is launched, it binds to the first unbound pipe number, which is typically `0`. Only `0` was being checked by the script earlier, but now it will go through all the possible pipe numbers by default. If all of them are a miss, there might be an issue with your system or Discord installation.
