### ISSUE TITLE
[FEATURE REQUEST] More dynamic buttons

### ISSUE THREAD

**Issue by jacobmix** [phin05/discord-rich-presence-plex#53]
Like TheTVDB or if possible MAL, AniList, and AniDB.
Tho i imagine if Plex doesn't have the info needed it wouldn't be easy to implement.
May also be a problem if Discord Rich Presence has a limit on the amount of buttons.
Edit: Seems like Discord only allows 2 buttons. Was hopping for 4, but will just have to pick the best fitting 2...
Tho i'd like to use TheTVDB if it's a show, and not when it's a movie. Would suck if TheTVDB took a button spot with movies.

**Comment by zluckytraveler** [comment]
@jacobmix I'm fairly certain that you wouldn't be able to differentiate what would or would not use TVDB, as the program is just pulling the media id number and matching with the metadata provider. SO for instance, since TVDB has both movies and television series it would still pick up the movie if it is in their database and matches the media id number that is given in Plex. 

As for using an Anime metadata provider, you'll likely have a lot of unmatched id numbers since those are not natively part of Plex and are converted to match what is currently in the database. FYI, TVDB is going to be the best source to match for Anime series.

**Comment by phin05** [comment]
Support for TheTVDB has been added in [v2.6.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.6.0). Use `dynamic:thetvdb`.

> MAL, AniList, and AniDB

Plex metadata has IDs only for IMDb, TMDB and TheTVDB and there doesn't seem to be any way to search using those IDs on these sites.

> Tho i'd like to use TheTVDB if it's a show, and not when it's a movie

Add the `mediaTypes` property:

```yaml
  buttons:
    - label: TheTVDB
      url: dynamic:thetvdb
      mediaTypes:
        - episode
```
