### ISSUE TITLE
Keeps Disconnecting....

### ISSUE THREAD

**Issue by zluckytraveler** [phin05/discord-rich-presence-plex#59]
For some reason the application keeps disconnecting and just stops working, it's very irregular as to when it happens. It can be while I am streaming or not streaming, or even right at the beginning of when I start the application.

This is the last information in the output, every time.
`[INFO] Disconnecting Discord IPC Pipe`

**Comment by phin05** [comment]
I'm closing this as stale.

This isn't reproducible and there haven't been any other reports like this. I think it might be a connectivity issue on your machine which is outside the scope of this project.

Feel free to post a comment if you believe otherwise, after testing again using the latest version.
