### ISSUE TITLE
Not connecting to correct discord client

### ISSUE THREAD

**Issue by Hinatabestwaifu** [phin05/discord-rich-presence-plex#63]
when i first used it it connect to the correct client and displayed my rich presence but the next morning i tried to launch it it wasn't showing my rich presence because it somehow got linked to the PTB version of discord which is not what i want it showing on. i tried to uninstall ptb and removed all the files pertaining to it but it still is just stuck on only wanting to connect to the PTB client. i turned on the write-to-file config to try to give you more data to work with 

this is the log of it connect to ptb: https://files.catbox.moe/bhactg.log

and then when ptb isn't running but normal discord is, it gives me this https://files.catbox.moe/t6lb2x.log

**Comment by phin05** [comment]
This should be fixed in [v2.4.2](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.4.2).

Discord's IPC pipe name can end with a number in the range of `0-9`. When a Discord client is launched, it binds to the first unbound pipe number, which is typically `0`. Only `0` was being checked by the script earlier, but now it will go through all the possible pipe numbers by default. If all of them are a miss, there might be an issue with your system or Discord installation.
